# -*- coding: utf-8 -*-
"""blinkit_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Kriz-21/pythonblinkit/blob/main/blinkit_python.ipynb

## ** DATA ANALYSIS PYTHON PROJECT - BLINKIT ANALYSIS **

## **Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### **Import Dataset**"""

url="https://raw.githubusercontent.com/Kriz-21/pythonblinkit/main/blinkit_data.csv"
df = pd.read_csv (url)

"""### **Sample Data**"""

df.head(20)

df.tail(10)

df.shape

"""### **Size of Dataset**"""

print("Size of Data:", df.shape)

"""### **Field name column**"""

df.columns

df.dtypes

"""### **Data Clening**"""

print (df['Item Fat Content'].unique())

df['Item Fat Content'] = df['Item Fat Content'].replace({'LF':'Low Fat',
                                                         'low fat': 'Low Fat',
                                                          'reg':'Regular',
                                                         })
print(df['Item Fat Content'].unique())

"""## **Business Requirement**

### **KPI'S Requiremnt**
"""

#Total Sales
total_sales = df['Sales'].sum

#Average Sales
avg_sales = df['Sales'].mean()

#No of item sold
no_of_items_sold = df['Sales'].count()

#Average Rating
avg_rating = df['Rating'].mean()

"""#### **Display**"""



print(type(total_sales))

df.columns

total_sales = df["Sales"].sum()
avg_sales = df["Sales"].mean()
no_of_items_sold = df["Item Identifier"].count()
avg_rating = df["Rating"].mean()

print(f"Total Sales : ${total_sales:,.0f}")
print(f"Average Sales : ${avg_sales:,.1f}")
print(f"No of Item Sold: {no_of_items_sold:,.0f}")
print(f"Average Rating: {avg_rating:,.1f}")

"""### **Charts Requirement**

##  1. Total sales by fat content
##  2. Total sales by item type
##  3. Fat content by outlet for total sales
"""

import matplotlib.pyplot as plt
# 1.pie chart

Sales_by_fat = df.groupby('Item Fat Content')['Sales'].sum()

plt.pie(Sales_by_fat,
        labels=Sales_by_fat.index,
        autopct='%1.1f%%',
        startangle=90)

plt.title('Sales By Fat Content')
plt.axis('equal')   # makes circle perfect
plt.show()

"""#### **Total Sales By Item Type**"""

import matplotlib.pyplot as plt

Sales_by_type = df.groupby('Item Type')['Sales'].sum().sort_values(ascending=False)

plt.figure(figsize=(10,6))
bars = plt.bar(Sales_by_type.index, Sales_by_type.values)

plt.xticks(rotation=90)
plt.xlabel('Item Type')
plt.ylabel('Total Sales')
plt.title('Total Sales By Item Type')

# Add value labels on top of bars
for bar in bars:
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height(),
             f'{bar.get_height():,.0f}',
             ha='center',
             va='bottom',
             fontsize=8)

plt.tight_layout()
plt.show()

"""#### **Fat Content By Outlet For Total Sales**"""

import matplotlib.pyplot as plt

grouped = df.groupby(['Outlet Location Type', 'Item Fat Content'])['Sales'].sum().unstack()

# keep order and avoid error
grouped = grouped.reindex(columns=['Low Fat', 'Regular'])

ax = grouped.plot(kind='bar', figsize=(8,5),
                  title='Outlet Tier by Item Fat Content')

plt.xlabel('Outlet Location Tier')
plt.ylabel('Total Sales')
plt.legend(title='Item Fat Content')
plt.tight_layout()
plt.show()

"""#### **Total Sales By Outlet Establishment**"""

import matplotlib.pyplot as plt

Sales_by_year = df.groupby('Outlet Establishment Year')['Sales'].sum().sort_index()

plt.figure(figsize=(9,5))
plt.plot(Sales_by_year.index,
         Sales_by_year.values,
         marker='o',
         linestyle='-')

plt.xlabel('Outlet Establishment Year')
plt.ylabel('Total Sales')
plt.title('Total Sales by Outlet Establishment Year')

# Add data labels
for x, y in zip(Sales_by_year.index, Sales_by_year.values):
    plt.text(x, y,
             f'{y:,.0f}',
             ha='center',
             va='bottom',
             fontsize=8)

plt.tight_layout()
plt.show()

"""#### **Sales By Outlet Size**"""

import matplotlib.pyplot as plt

# handle missing values
df['Outlet Size'] = df['Outlet Size'].fillna('Unknown')

Sales_by_size = df.groupby('Outlet Size')['Sales'].sum()

plt.figure(figsize=(5,5))
plt.pie(Sales_by_size,
        labels=Sales_by_size.index,
        autopct='%1.1f%%',
        startangle=90)

plt.title('Sales Distribution by Outlet Size')
plt.tight_layout()
plt.show()

"""#### **Sales By Outlet Location**"""

import seaborn as sns
import matplotlib.pyplot as plt

Sales_by_location = df.groupby('Outlet Location Type')['Sales'].sum().reset_index()
Sales_by_location = Sales_by_location.sort_values('Sales', ascending=False)

plt.figure(figsize=(8,4))

ax = sns.barplot(x='Sales',
                 y='Outlet Location Type',
                 data=Sales_by_location)

plt.title('Total Sales By Outlet Location Type')
plt.xlabel('Total Sales')
plt.ylabel('Outlet Location Type')

plt.tight_layout()
plt.show()

